### ISSUE TITLE
Request: Update LibTorch library

### ISSUE THREAD

**Issue by GistKen** [janestreet/torch#1] opened 2023-07-02 06:00 UTC
Hey! Just playing around with the repo and I thought this little bit could be useful to somebody. Would it be possible to update the included LibTorch library or perhaps instructions?

I am on NVIDIA 12.2 and had to download the LibTorch c++ version to the latest nightly build (cuda 12.1) to get opam to install torch:
`https://download.pytorch.org/libtorch/nightly/cu121/libtorch-cxx11-abi-shared-with-deps-latest.zip`

Previously, it was failing for me but once I changed it over to this library, it installed.

**Comment by mwlon** [comment] 2023-07-05 14:18
To be clear - we don't include a libtorch installation. There are various ways you can configure the installation to find libtorch, following this chain: https://github.com/janestreet/torch/blob/master/src/config/discover.ml#L61. But we should have better instructions for this.

The title of the issue is currently "Update LibTorch library", but if I understand correctly, you're not asking us to upgrade our bindings (which currently work for libtorch 1.13) to 2.0, right? Though this is also something we're planning to do.

**Comment by vthemelis** [comment] 2023-07-08 12:27
@mwlon , it seems like there is a version of `libtorch` pulled in when installing torch via `opam`. I think that this comes in from the `libtorch` `opam` package that this library depends on. I can't find what pushes that package but it seems like the pulled version doesn't support Apple Silicon which is a bit annoying.

I am now trying to build this against a custom distribution of `libtorch` using the environment variable `LIBTORCH` but had to uninstall and reinstall the `torch` package for this. Is there another way to force rerun the dune build?

**Comment by mwlon** [comment] 2023-07-10 19:42
I was a bit unclear; we have OPAM libtorch as a dependency, but it's not the only way to configure this library to build with libtorch.

I think you might be able to install for mac by depending on libtorch=1.13.0+macos-x86_64 specifically and doing a clean build.

**Comment by GistKen** [comment] 2023-07-10 23:49
Would it be possible to update the instructions for how this package is used on different architectures?
Looking back at the original repository, there were some questions for building, etc.

**Comment by mwlon** [comment] 2023-07-11 21:24
I've made a documentation change that should go out with the next release and make this clearer.

**Comment by vthemelis** [comment] 2023-07-11 21:44
Thanks! More documentation would be great!

Unfortunately, for Mac with Apple Silicon (arm64) it's not possible to install this package using the happy-path `opam` route. I wrote about how I installed it here if that helps: https://github.com/LaurentMazare/ocaml-torch/issues/76

The main things that were confusing for me where:
* `torch` versioning is peculiar: there is a version `v16.0.0` which is the newest and derives from the Jane Street package but there's also an older `0.17` version.
* `libtorch`, the dependency of `torch` is marked as incompatible with non-x86 machines which makes `torch` itself by default incompatible with Apple Silicon. See the issue above about how I overcame this.

**Comment by mwlon** [comment] 2023-07-12 17:35
Yeah the versioning is weird, and that's mostly because of our internal versioning system for public packages. All Jane Street OPAM packages are on v16.x.y now.

I understand the Apple silicon issue now. I think I'll turn libtorch into an optional dependency, making the choice more explicit. It seems OPAM libtorch often doesn't cover users' needs, and many will need a different installation method (for GPUs, Windows, ARM).

**Comment by Fa-C-Shus** [comment] 2023-07-13 00:21
I am very new to ocaml, dume & opam. I was very excited to find this repo and opam torch, but I do have Apple Silicon. I'm thinking of killing too many birds with one stone. If I created an Apple Silicon version of this, maybe mtorch (metal torch), would there be any interest, or should I somehow try to fork and add the feature to the janestreet repo?

**Comment by mwlon** [comment] 2023-07-13 22:55
You can already use this with apple silicon - you just need to install libtorch somewhere, uninstall this package, and reinstall it with the LIBTORCH variable pointing to where you unpacked libtorch.

**Comment by Fa-C-Shus** [comment] 2023-07-14 00:47
> You can already use this with apple silicon - you just need to install libtorch somewhere, uninstall this package, and reinstall it with the LIBTORCH variable pointing to where you unpacked libtorch.

I appreciate the guidance; I'm struggling getting the library installed 

![image](https://github.com/janestreet/torch/assets/2677797/84e099c9-a89a-4813-8746-f67fe0a82ef6)
I did download libtorch 2.0, then retried with 1.13.1 and 1.13.0 then set the env vars for the libtorch dir and the include and lib directories.

**Comment by Fa-C-Shus** [comment] 2023-07-14 00:48
Do I need to downgrade ocaml?

**Comment by vthemelis** [comment] 2023-07-14 07:29
You need to downgrade OCaml to 4.14. See https://github.com/LaurentMazare/ocaml-torch/issues/76#issuecomment-1627318488

Also, you're not going to be able to install this with the usual opam command.

**Comment by mwlon** [comment] 2023-10-18 15:12
Closing this since we've both done the original ask (update to 12.0) (documentation update pending) and written about the Mac issue

**Closed as completed by mwlon** 2023-10-18 15:12 UTC
Labels: forwarded-to-js-devs

**Comment by arbipher** [comment] 2024-01-25 02:24
Is there some specific reasons to keep Option 1 (OPAM switch) as **CPU only**?

I also read issue #8 and I can build and run [locally](https://pytorch.org/get-started/locally/) with wsl2, ubuntu, libtorch 2.1.2 with CUDA-support.

```console
$ dune exec ./examples/basics/basics.exe
cuda available: true
cudnn available: true
42
[ CPUFloatType{} ]
```

I wonder if it's possible that libtorch CUDA can work as an opam package or a version for `libtorch` on opam?
